{
 "title": "TemporalSeries",
 "time": { "from": "2024-05-11T10:27:44.900Z", "to": "2024-05-11T11:00:46.721Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Light",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM sensor_light "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM sensor_temperature "
    }
   ]
  },
  {
   "title": "Motion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM sensor_motion "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM sensor_humidity"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM sensor_airquality "
    }
   ]
  },
  {
   "title": "Sound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM sensor_sound"
    }
   ]
  },
  {
   "title": "Water",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM sensor_water"
    }
   ]
  },
  {
   "title": "Door Window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM sensor_doorwindow"
    }
   ]
  }
 ]
}